{% set version = "7.0.0" %}
{% set sha256 = "8bc1f844e6cbde1b652c19c1edebc1864456fd9c78b8c1bea038e51b363fe222" %}

package:
  name: llvm-meta
  version: {{ version }}

source:
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

test:
  commands:
    - echo 'Meta package for tracking llvm version'

about:
  home: http://github.com/conda-forge/llvm-meta-feedstock
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Meta package for tracking llvm version'

extra:
  recipe-maintainers:
    - isuruf
