{% set version = "7.0.1" %}
{% set sha256 = "a38dfc4db47102ec79dcc2aa61e93722c5f6f06f0a961073bd84b78fb949419b" %}

package:
  name: llvm-meta
  version: {{ version }}

source:
  url: http://llvm.org/releases/{{ version }}/llvm-{{ version }}.src.tar.xz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

test:
  commands:
    - echo 'Meta package for tracking llvm version'

about:
  home: http://github.com/conda-forge/llvm-meta-feedstock
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Meta package for tracking llvm version'

extra:
  recipe-maintainers:
    - isuruf
