travis:
  secure:
    BINSTAR_TOKEN: H1B/hTVCqSEiAGdPcOjbAW1nwJiFLC3wloEjtcGBsse3FrqRl6W5fHlY01g8vuL3uwyw0HGEoZKkMita0gghpkYgN+VLdJUFlErx0zj4G97zk/2yXwL5GwnG67TK1v2w+frCD8WyEq4jkMgKMTRTigAijGlLSU5Vi8rgqXFfKjri0GdT6JDDqc2Kr7YWLeFmv8QaK66ko/6xSZmAOeZZGOMEMl/CkBLJtuv9BeDbq+rpqmnw0EOhoIZ9YiIRCR2DUJPrXSzTNqKiqg0BMA4kXJFVZN0omudvukbOkLQ+uBQJyihY7zH6YBdFBtPDe55oVWMKC+caFTEqghqchOASRk8XuY42/Ciu5EvoH5YAEKgbnx3x/MQh5w9gLlzRUwY43I3ygHRdr3kxvvcP0mXmi3kIsdBTklrX1IgwDOvWTp/uOxxPBKVndNp8lMA1NLta1+c6+x3CGxgwRyNHYddf2q6eE7fOcPdFGuBSQD/M0ojKY46gWmyYM5dQwtNuXs1CpayLIQjtXKc5qCXG/UC9NlVDaTqVW1m+TbSO0vZQrs7CmEVvRxDHSv1BudwCWtrFnfwAv9btvjJBFpryEXU85ZvAgVKx8oiAawXNhndc37emAje4gUBxFFBGvUhnQF4nNF3brvoDypJyE3sOoQRM0h5dVaH+ePiPMieYHIoPQ/s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
